CREATE OR ALTER PROCEDURE SP_ATUALIZA_FERIADO_TEMPO
@ANO DATE
AS
BEGIN
    BEGIN TRY
        DECLARE @FERIADO VARCHAR(100), @DATA DATE
        DECLARE @C_FERIADO CURSOR

        SET @C_FERIADO = CURSOR FOR
        SELECT DATA, DESCRICAO FROM DIM_FERIADO

        OPEN @C_FERIADO

        FETCH @C_FERIADO INTO @DATA, @FERIADO

        WHILE (@@FETCH_STATUS = 0)
        BEGIN
            UPDATE DIM_TEMPO
            SET FERIADO = @FERIADO, FL_FERIADO = 'SIM'
            WHERE DATA = @DATA

            FETCH @C_FERIADO INTO @DATA, @FERIADO
        END

        CLOSE @C_FERIADO
        DEALLOCATE @C_FERIADO
    END TRY
    BEGIN CATCH
        -- Adicione o tratamento de erro aqui (por exemplo, PRINT ERROR_MESSAGE())
    END CATCH
END
