create or alter procedure sp_dim_produto(@data_carga datetime)
as
begin
   DECLARE @COD_PRODUTO INT
   DECLARE @PRODUTO VARCHAR(100)
   DECLARE @COD_CATEGORIA INT
   DECLARE @CATEGORIA VARCHAR(100)

    DECLARE CUR CURSOR FOR
    SELECT COD_PRODUTO,PRODUTO,COD_CATEGORIA,CATEGORIA
    FROM TB_AUX_PRODUTO 
	WHERE DATA_CARGA = @data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_PRODUTO WHERE COD_PRODUTO = @COD_PRODUTO) AND @COD_PRODUTO IS NOT NULL
        BEGIN
            INSERT INTO DIM_PRODUTO (COD_PRODUTO,PRODUTO,COD_CATEGORIA,CATEGORIA)
            VALUES (@COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA)
        END
        FETCH NEXT FROM CUR INTO @COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA
    END
    
    CLOSE CUR;
    DEALLOCATE CUR;
end


-- Teste

exec sp_dim_produto '20240324'

select * from dim_produto